import type { PresetGroup } from './types';

export const fujifilmPresets: PresetGroup = {
  id: 'fujifilm',
  name: 'Fujifilm',
  presets: [
    {
      id: 'provia',
      name: 'Provia/Standard',
      description: 'Balanced, true-to-life color reproduction',
      edits: {
        contrast: 5,
        vibrance: 8,
        saturation: 5,
        highlights: -5,
        shadows: 5,
        toneCurve: {
          rgb: [{ x: 0, y: 0 }, { x: 0.25, y: 0.23 }, { x: 0.5, y: 0.5 }, { x: 0.75, y: 0.77 }, { x: 1, y: 1 }],
          red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        },
        hsl: {
          hue: [0, 0, 0, 0, 0, 0, 0, 0],
          saturation: [5, 5, 0, 5, 0, 5, 0, 0],
          luminance: [0, 0, 0, 0, 0, 0, 0, 0],
        },
        colorGrading: {
          shadows: { hue: 0, saturation: 0, luminance: 0 },
          midtones: { hue: 0, saturation: 0, luminance: 0 },
          highlights: { hue: 0, saturation: 0, luminance: 0 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'velvia',
      name: 'Velvia/Vivid',
      description: 'High contrast, deeply saturated colors',
      edits: {
        contrast: 25,
        vibrance: 20,
        saturation: 30,
        highlights: -10,
        shadows: -15,
        blacks: -10,
        toneCurve: {
          rgb: [{ x: 0, y: 0 }, { x: 0.25, y: 0.18 }, { x: 0.5, y: 0.52 }, { x: 0.75, y: 0.83 }, { x: 1, y: 1 }],
          red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 0.5, y: 0.52 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0 }, { x: 0.5, y: 0.54 }, { x: 1, y: 1 }],
        },
        hsl: {
          hue: [0, 5, 0, -5, 0, -5, 0, 0],
          saturation: [15, 10, 10, 20, 10, 25, 10, 5],
          luminance: [0, 0, 5, 5, 0, -10, 0, 0],
        },
        colorGrading: {
          shadows: { hue: 240, saturation: 10, luminance: -5 },
          midtones: { hue: 0, saturation: 0, luminance: 0 },
          highlights: { hue: 45, saturation: 8, luminance: 5 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'astia',
      name: 'Astia/Soft',
      description: 'Soft tones, low contrast, flattering skin tones',
      edits: {
        contrast: -10,
        vibrance: 10,
        saturation: 8,
        highlights: 10,
        shadows: 15,
        toneCurve: {
          rgb: [{ x: 0, y: 0.02 }, { x: 0.25, y: 0.27 }, { x: 0.5, y: 0.52 }, { x: 0.75, y: 0.75 }, { x: 1, y: 0.98 }],
          red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        },
        hsl: {
          hue: [0, 5, 0, 0, 0, 0, 0, 5],
          saturation: [5, 10, 5, 5, 0, 0, 5, 10],
          luminance: [5, 5, 0, 0, 0, 0, 0, 5],
        },
        colorGrading: {
          shadows: { hue: 30, saturation: 5, luminance: 3 },
          midtones: { hue: 0, saturation: 0, luminance: 0 },
          highlights: { hue: 40, saturation: 5, luminance: 0 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'classic-chrome',
      name: 'Classic Chrome',
      description: 'Muted colors, deep shadows, journalistic feel',
      edits: {
        contrast: 20,
        vibrance: -5,
        saturation: -15,
        highlights: -10,
        shadows: -10,
        blacks: -5,
        toneCurve: {
          rgb: [{ x: 0, y: 0.02 }, { x: 0.25, y: 0.2 }, { x: 0.5, y: 0.48 }, { x: 0.75, y: 0.78 }, { x: 1, y: 0.97 }],
          red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0 }, { x: 0.5, y: 0.46 }, { x: 1, y: 0.96 }],
        },
        hsl: {
          hue: [5, 5, 0, -5, 0, 0, 0, 0],
          saturation: [-20, -10, -10, -5, -5, -5, -10, -15],
          luminance: [-5, 0, 5, 0, 0, -5, 0, 0],
        },
        colorGrading: {
          shadows: { hue: 40, saturation: 15, luminance: -3 },
          midtones: { hue: 35, saturation: 5, luminance: 0 },
          highlights: { hue: 210, saturation: 10, luminance: 0 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'classic-negative',
      name: 'Classic Negative',
      description: 'High contrast, desaturated, warm highlights and cool shadows',
      edits: {
        contrast: 25,
        vibrance: -10,
        saturation: -20,
        highlights: -5,
        shadows: -20,
        blacks: -10,
        toneCurve: {
          rgb: [{ x: 0, y: 0.03 }, { x: 0.25, y: 0.18 }, { x: 0.5, y: 0.5 }, { x: 0.75, y: 0.8 }, { x: 1, y: 0.97 }],
          red: [{ x: 0, y: 0.02 }, { x: 0.5, y: 0.52 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 0.5, y: 0.48 }, { x: 1, y: 0.97 }],
          blue: [{ x: 0, y: 0.03 }, { x: 0.5, y: 0.46 }, { x: 1, y: 0.94 }],
        },
        hsl: {
          hue: [10, 10, 0, -10, -5, 0, 5, 10],
          saturation: [-15, -10, -10, -15, -10, -10, -10, -15],
          luminance: [0, 5, 5, -5, 0, -5, 0, 0],
        },
        colorGrading: {
          shadows: { hue: 210, saturation: 20, luminance: -5 },
          midtones: { hue: 30, saturation: 8, luminance: 0 },
          highlights: { hue: 40, saturation: 18, luminance: 3 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'pro-neg-hi',
      name: 'PRO Neg. Hi',
      description: 'Moderate contrast, low saturation, portrait-optimized',
      edits: {
        contrast: 15,
        vibrance: -5,
        saturation: -12,
        highlights: -8,
        shadows: 5,
        toneCurve: {
          rgb: [{ x: 0, y: 0 }, { x: 0.25, y: 0.22 }, { x: 0.5, y: 0.5 }, { x: 0.75, y: 0.78 }, { x: 1, y: 1 }],
          red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        },
        hsl: {
          hue: [0, 5, 0, 0, 0, 0, 0, 0],
          saturation: [-10, -5, -5, -5, 0, 0, -5, -8],
          luminance: [5, 5, 0, 0, 0, 0, 0, 5],
        },
        colorGrading: {
          shadows: { hue: 30, saturation: 8, luminance: 0 },
          midtones: { hue: 0, saturation: 0, luminance: 0 },
          highlights: { hue: 40, saturation: 5, luminance: 0 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'pro-neg-std',
      name: 'PRO Neg. Std',
      description: 'Flat, low contrast, maximum editing latitude',
      edits: {
        contrast: -15,
        vibrance: -5,
        saturation: -10,
        highlights: 10,
        shadows: 15,
        toneCurve: {
          rgb: [{ x: 0, y: 0.03 }, { x: 0.25, y: 0.27 }, { x: 0.5, y: 0.5 }, { x: 0.75, y: 0.73 }, { x: 1, y: 0.97 }],
          red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        },
        hsl: {
          hue: [0, 0, 0, 0, 0, 0, 0, 0],
          saturation: [-8, -5, -5, -5, 0, 0, -5, -5],
          luminance: [0, 0, 0, 0, 0, 0, 0, 0],
        },
        colorGrading: {
          shadows: { hue: 0, saturation: 0, luminance: 0 },
          midtones: { hue: 0, saturation: 0, luminance: 0 },
          highlights: { hue: 0, saturation: 0, luminance: 0 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'eterna',
      name: 'Eterna',
      description: 'Cinematic, low saturation, lifted shadows',
      edits: {
        contrast: -10,
        vibrance: -10,
        saturation: -25,
        highlights: -15,
        shadows: 20,
        blacks: 10,
        toneCurve: {
          rgb: [{ x: 0, y: 0.08 }, { x: 0.25, y: 0.3 }, { x: 0.5, y: 0.5 }, { x: 0.75, y: 0.7 }, { x: 1, y: 0.92 }],
          red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0.02 }, { x: 0.5, y: 0.52 }, { x: 1, y: 0.98 }],
        },
        hsl: {
          hue: [0, 0, 0, 0, 5, 5, 0, 0],
          saturation: [-15, -10, -10, -10, -5, -5, -10, -15],
          luminance: [0, 0, 5, 5, 0, -5, 0, 0],
        },
        colorGrading: {
          shadows: { hue: 210, saturation: 12, luminance: 5 },
          midtones: { hue: 200, saturation: 5, luminance: 0 },
          highlights: { hue: 45, saturation: 8, luminance: -3 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'eterna-bleach-bypass',
      name: 'Eterna Bleach Bypass',
      description: 'Extreme contrast, very low saturation, gritty look',
      edits: {
        contrast: 40,
        vibrance: -15,
        saturation: -35,
        highlights: -20,
        shadows: -25,
        blacks: -15,
        whites: 10,
        toneCurve: {
          rgb: [{ x: 0, y: 0 }, { x: 0.2, y: 0.1 }, { x: 0.4, y: 0.38 }, { x: 0.6, y: 0.65 }, { x: 0.8, y: 0.88 }, { x: 1, y: 1 }],
          red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        },
        hsl: {
          hue: [0, 0, 0, 0, 0, 0, 0, 0],
          saturation: [-30, -25, -20, -20, -15, -15, -20, -25],
          luminance: [0, 0, 5, 5, 0, -5, 0, 0],
        },
        colorGrading: {
          shadows: { hue: 210, saturation: 8, luminance: -5 },
          midtones: { hue: 0, saturation: 0, luminance: 0 },
          highlights: { hue: 45, saturation: 5, luminance: 3 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'nostalgic-negative',
      name: 'Nostalgic Negative',
      description: 'Amber warmth, cyan shadows, vintage character',
      edits: {
        contrast: 15,
        vibrance: -5,
        saturation: -10,
        highlights: -5,
        shadows: -5,
        toneCurve: {
          rgb: [{ x: 0, y: 0.02 }, { x: 0.25, y: 0.23 }, { x: 0.5, y: 0.5 }, { x: 0.75, y: 0.77 }, { x: 1, y: 0.98 }],
          red: [{ x: 0, y: 0 }, { x: 0.5, y: 0.52 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0.04 }, { x: 0.5, y: 0.46 }, { x: 1, y: 0.92 }],
        },
        hsl: {
          hue: [5, 10, 5, -5, -5, 0, 5, 10],
          saturation: [-5, 5, 5, -10, -5, -10, 0, -5],
          luminance: [0, 5, 5, 0, 0, -5, 0, 0],
        },
        colorGrading: {
          shadows: { hue: 190, saturation: 18, luminance: -3 },
          midtones: { hue: 35, saturation: 10, luminance: 0 },
          highlights: { hue: 40, saturation: 15, luminance: 3 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'reala-ace',
      name: 'Reala ACE',
      description: 'True-to-life, slight vibrance boost, color-accurate',
      edits: {
        contrast: 3,
        vibrance: 12,
        saturation: 3,
        highlights: -3,
        shadows: 3,
        toneCurve: {
          rgb: [{ x: 0, y: 0 }, { x: 0.25, y: 0.25 }, { x: 0.5, y: 0.5 }, { x: 0.75, y: 0.75 }, { x: 1, y: 1 }],
          red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        },
        hsl: {
          hue: [0, 0, 0, 0, 0, 0, 0, 0],
          saturation: [3, 3, 0, 5, 3, 3, 0, 0],
          luminance: [0, 0, 0, 0, 0, 0, 0, 0],
        },
        colorGrading: {
          shadows: { hue: 0, saturation: 0, luminance: 0 },
          midtones: { hue: 0, saturation: 0, luminance: 0 },
          highlights: { hue: 0, saturation: 0, luminance: 0 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'acros',
      name: 'ACROS',
      description: 'Fine-grain monochrome, rich tonal range, deep blacks',
      edits: {
        contrast: 20,
        saturation: -100,
        highlights: -5,
        shadows: -10,
        blacks: -10,
        toneCurve: {
          rgb: [{ x: 0, y: 0 }, { x: 0.25, y: 0.2 }, { x: 0.5, y: 0.5 }, { x: 0.75, y: 0.8 }, { x: 1, y: 1 }],
          red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        },
        hsl: {
          hue: [0, 0, 0, 0, 0, 0, 0, 0],
          saturation: [0, 0, 0, 0, 0, 0, 0, 0],
          luminance: [5, 10, 15, 5, -5, -10, 5, 10],
        },
        colorGrading: {
          shadows: { hue: 0, saturation: 0, luminance: -3 },
          midtones: { hue: 0, saturation: 0, luminance: 0 },
          highlights: { hue: 0, saturation: 0, luminance: 3 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'acros-ye',
      name: 'ACROS + Ye',
      description: 'ACROS with yellow filter — darkened blues, brightened yellows',
      edits: {
        contrast: 20,
        saturation: -100,
        highlights: -5,
        shadows: -10,
        blacks: -10,
        toneCurve: {
          rgb: [{ x: 0, y: 0 }, { x: 0.25, y: 0.2 }, { x: 0.5, y: 0.5 }, { x: 0.75, y: 0.8 }, { x: 1, y: 1 }],
          red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        },
        hsl: {
          hue: [0, 0, 0, 0, 0, 0, 0, 0],
          saturation: [0, 0, 0, 0, 0, 0, 0, 0],
          luminance: [5, 10, 25, 5, -10, -20, 5, 10],
        },
        colorGrading: {
          shadows: { hue: 0, saturation: 0, luminance: -3 },
          midtones: { hue: 0, saturation: 0, luminance: 0 },
          highlights: { hue: 0, saturation: 0, luminance: 3 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'acros-r',
      name: 'ACROS + R',
      description: 'ACROS with red filter — dramatic skies, brightened reds',
      edits: {
        contrast: 22,
        saturation: -100,
        highlights: -5,
        shadows: -12,
        blacks: -10,
        toneCurve: {
          rgb: [{ x: 0, y: 0 }, { x: 0.25, y: 0.2 }, { x: 0.5, y: 0.5 }, { x: 0.75, y: 0.8 }, { x: 1, y: 1 }],
          red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        },
        hsl: {
          hue: [0, 0, 0, 0, 0, 0, 0, 0],
          saturation: [0, 0, 0, 0, 0, 0, 0, 0],
          luminance: [20, 15, 10, -10, -15, -30, 5, 15],
        },
        colorGrading: {
          shadows: { hue: 0, saturation: 0, luminance: -5 },
          midtones: { hue: 0, saturation: 0, luminance: 0 },
          highlights: { hue: 0, saturation: 0, luminance: 5 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'acros-g',
      name: 'ACROS + G',
      description: 'ACROS with green filter — brightened greens, smooth skin',
      edits: {
        contrast: 20,
        saturation: -100,
        highlights: -5,
        shadows: -10,
        blacks: -10,
        toneCurve: {
          rgb: [{ x: 0, y: 0 }, { x: 0.25, y: 0.2 }, { x: 0.5, y: 0.5 }, { x: 0.75, y: 0.8 }, { x: 1, y: 1 }],
          red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        },
        hsl: {
          hue: [0, 0, 0, 0, 0, 0, 0, 0],
          saturation: [0, 0, 0, 0, 0, 0, 0, 0],
          luminance: [-5, 5, 15, 25, 5, -15, -5, -5],
        },
        colorGrading: {
          shadows: { hue: 0, saturation: 0, luminance: -3 },
          midtones: { hue: 0, saturation: 0, luminance: 0 },
          highlights: { hue: 0, saturation: 0, luminance: 3 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'monochrome',
      name: 'Monochrome',
      description: 'Classic black and white, medium contrast',
      edits: {
        contrast: 10,
        saturation: -100,
        highlights: -5,
        shadows: 5,
        toneCurve: {
          rgb: [{ x: 0, y: 0 }, { x: 0.25, y: 0.23 }, { x: 0.5, y: 0.5 }, { x: 0.75, y: 0.77 }, { x: 1, y: 1 }],
          red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        },
        hsl: {
          hue: [0, 0, 0, 0, 0, 0, 0, 0],
          saturation: [0, 0, 0, 0, 0, 0, 0, 0],
          luminance: [0, 5, 10, 5, 0, -5, 0, 0],
        },
        colorGrading: {
          shadows: { hue: 0, saturation: 0, luminance: 0 },
          midtones: { hue: 0, saturation: 0, luminance: 0 },
          highlights: { hue: 0, saturation: 0, luminance: 0 },
          global: { hue: 0, saturation: 0, luminance: 0 },
        },
      },
    },
    {
      id: 'sepia',
      name: 'Sepia',
      description: 'Warm brown-toned monochrome, vintage feel',
      edits: {
        contrast: 10,
        saturation: -100,
        highlights: -5,
        shadows: 5,
        toneCurve: {
          rgb: [{ x: 0, y: 0.02 }, { x: 0.25, y: 0.24 }, { x: 0.5, y: 0.5 }, { x: 0.75, y: 0.76 }, { x: 1, y: 0.98 }],
          red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
          blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        },
        hsl: {
          hue: [0, 0, 0, 0, 0, 0, 0, 0],
          saturation: [0, 0, 0, 0, 0, 0, 0, 0],
          luminance: [0, 5, 10, 5, 0, -5, 0, 0],
        },
        colorGrading: {
          shadows: { hue: 35, saturation: 30, luminance: -3 },
          midtones: { hue: 35, saturation: 20, luminance: 0 },
          highlights: { hue: 40, saturation: 15, luminance: 3 },
          global: { hue: 37, saturation: 20, luminance: 0 },
        },
      },
    },
  ],
};
